"""Public component catalogs shared by all ZhiXing authoring surfaces."""

from .builtins import (
    BUILTIN_COMPONENT_CATALOG,
    BuiltInAvailability,
    BuiltInComponentCatalog,
    BuiltInComponentResolver,
    BuiltInComponentSpec,
    BuiltInComponentUnavailableError,
    create_builtin_resolver,
)
from .external import (
    ENTRY_POINT_GROUP,
    CatalogComponentResolver,
    ComponentCatalog,
    ComponentCatalogEntry,
    ComponentCatalogError,
    ComponentDiscoveryError,
    DiscoveredComponentEnvironment,
    DiscoveryReport,
    ExternalComponentError,
    PluginCandidate,
    PluginLoadFailure,
    PluginOrigin,
    create_component_resolver,
    discover_components,
    empty_component_environment,
    enumerate_component_plugins,
    load_component_plugins,
    select_component_plugins,
)

__all__ = [
    "BUILTIN_COMPONENT_CATALOG",
    "BuiltInAvailability",
    "BuiltInComponentCatalog",
    "BuiltInComponentResolver",
    "BuiltInComponentSpec",
    "BuiltInComponentUnavailableError",
    "CatalogComponentResolver",
    "ComponentCatalog",
    "ComponentCatalogEntry",
    "ComponentCatalogError",
    "ComponentDiscoveryError",
    "DiscoveredComponentEnvironment",
    "DiscoveryReport",
    "ENTRY_POINT_GROUP",
    "ExternalComponentError",
    "PluginCandidate",
    "PluginLoadFailure",
    "PluginOrigin",
    "create_component_resolver",
    "create_builtin_resolver",
    "discover_components",
    "empty_component_environment",
    "enumerate_component_plugins",
    "load_component_plugins",
    "select_component_plugins",
]
