from abc import ABC, abstractmethod
from typing import List, Any, Optional
from zhixing.utils.utils import get_plugin_logger

class BaseLLM(ABC):
    """
    LLM Adapter
    Defined the standards for how to interact with the underlying models (OpenAI, DeepSeek, LocalLLM)
    """

    _pipeline_phase = "🧠 LLM" 

    def __init__(self, api_key: str, model: str = "gpt-4o", base_url: Optional[str] = None, 
                 temperature: float = 0.1, max_tokens: int = 4096, **kwargs):
        
        self.api_key = api_key
        self.model = model
        self.base_url = base_url
        self.temperature = temperature
        self.max_tokens = max_tokens
        
        self.extra_kwargs = kwargs

        namespace = getattr(self.__class__, '__plugin_namespace__', 'llm.unknown')
        name = getattr(self.__class__, '__plugin_name__', self.__class__.__name__)
        self.logger = get_plugin_logger(phase=self._pipeline_phase, namespace=namespace, plugin_name=name)

    @abstractmethod
    def generate(self, prompt: str, images: Optional[List[str]] = None) -> str:
        """generate function

        Args:
            prompt (str): text prompt
            images (List[str], optional): List of image paths. Defaults to None.

        Returns:
            str: The original text generated by the model
        """
        pass