from abc import ABC, abstractmethod
from typing import List, Any, Optional
from zhixing.core.agent.protocol import Action
from zhixing.core.agent.protocol import PerceptionResult, MemoryFragment, FragmentType, PerceptionInput, PlanResult, PlanInput
from zhixing.core.agent.protocol import VerifierInput, VerifierResult
from zhixing.knowledge.base import BaseKnowledgeSource
from zhixing.core.context import EnvironmentInfo
from zhixing.knowledge.formatter import format_knowledge

# ==========================================
# 1. Infrastructure Interfaces
# ==========================================
class BaseLLM(ABC):
    """
    LLM Adapter
    Defined the standards for how to interact with the underlying models (OpenAI, DeepSeek, LocalLLM)
    """
    @abstractmethod
    def generate(self, prompt: str, images: List[str] = None) -> str:
        """generate function

        Args:
            prompt (str): text prompt
            images (List[str], optional): List of image paths. Defaults to None.

        Returns:
            str: The original text generated by the model
        """
        pass

# ==========================================
# 2. Module Interfaces
# ==========================================
class BasePerception(ABC):
    """
    Base interface for all perception modules.

    A perception module observes the agent's environment and produces a structured, agent-readable representation of the current state.

    The environment may include, but is not limited to:
    - Visual GUI state (screenshot, UI layouts)
    - System-level capabilities (eg., exposed app APIs or tools)

    Perception modules are responsible for *observation and description only*.
    They must not perform planning, reasoning, or action execution.
    """
    @abstractmethod
    def perceive(self, perception_input: PerceptionInput) -> PerceptionResult:
        """Perform perception on the current environment state.

        This method is the core entry point of the perception module.
        It consumes raw observation inputs (e.g., screenshots or
        system-provided metadata) and produces a PerceptionResult
        that describes what the agent can currently observe.

        Args:
            perception_input (PerceptionInput): 
            A container of raw observation data.
            It currently includes:
             - screenshot_path: Paths to screenshots
             - width, height: screen dimensions

        Returns:
            PerceptionResult: 
            A unified perception output that currently contain:
             - mode (str): Identifier of the perception strategy name used
             - original_screenshot_path (str): Path to the original screenshot used as perception input.
             - elements (List[Dict[str, Any]]): A list of detected elements on the screen. 
             - metadata (Dict[str, Any]): Auxiliary metadata produced during perception.
             - data (Dict[str, Any]): Structured or global semantic information inferred from the screen.
             - marked_screenshot_path (Optional[str]): Optional path to a visualization image where detected elements are annotated on top of the original screenshot.
             - prompt_representation (str): A textual representation of the perception result that can be directly embedded into an LLM prompt. 
               This field allows the perception module to control how observations are presented to downstream reasoning modules.
             - visual_representations (List[str]): The final image returned to the reasoning component for viewing
        """
        pass

    @abstractmethod
    def _get_prompt_context(self, result: Any) -> str:
        """
        Generate a textual prompt context from the perception result.

        This method defines how the perception output is presented
        to language models. Different perception strategies may choose
        different prompt styles, such as:
        - Lists or tables of detected UI elements
        - Natural language summaries of the screen
        - Enumerations of available system APIs or tools
        - Hybrid descriptions combining visual and declarative information

        Args:
            result (Any): Any

        Returns:
            str: A human-readable textual description of the current environment, suitable for direct inclusion in an LLM prompt.
        
        """
        pass

class BaseMemory(ABC):
    def __init__(self, knowledge_source: BaseKnowledgeSource = None):
        """
        Initialize the memory module.

        Args:
            knowledge_source (BaseKnowledgeSource, optional): An optional external knowledge base (e.g., vector DB) 
                used for Retrieval-Augmented Generation (RAG). Defaults to None.
        """
        self.knowledge_source = knowledge_source
        self.knowledge_buffer: List[MemoryFragment] = []

    @abstractmethod
    def add(self, fragment: MemoryFragment):
        """Record a new event into memory.
        This method is called after every step to save the latest interaction.

        Args:
            fragment (MemoryFragment): fragment (MemoryFragment): The smallest unit of memory.
        Example:
            memory.add(MemoryFragment(
                role="user", 
                type=FragmentType.TEXT, 
                content="Open settings"
            ))
        """
        pass
    
    @abstractmethod
    def get_working_context(self) -> List[MemoryFragment]:
        """
        The return value must be a list of MemoryFragments.
        """
        pass

    # --- RAG / Knowledge Related Methods (Optional Usage) ---
    def load_knowledge(self, query: str):
        """
        [Slow Path] Retrieve relevant documents from the knowledge source based on a text query.
        This is typically used at the beginning of a task to load App manuals or general usage tips.
        The retrieved documents are converted into `MemoryFragment` (type=RAG_DOC) and stored in `self.knowledge_buffer`.
        
        Args:
            query (str): The search query.
        """
        source = self.knowledge_source

        if not source:
            return
    
        self.knowledge_buffer = []

        docs = source.search_docs(query)

        for doc in docs:
            formatted_content = format_knowledge(doc)

            frag = MemoryFragment(
                role="system",
                type=FragmentType.RAG_DOC,
                content=formatted_content,
                metadata={"category": doc.category}
            )

            self.knowledge_buffer.append(frag)

    # Fast Path
    def retrieve_experience(self, screenshot_path: str, task: str) -> Optional[Action]:
        """
        [Fast Path] Retrieve a specific executable action from experience memory.
        
        Args:
            screenshot_path (str): Path to the current screenshot.
            task (str): Current task description.
        
        Returns:
            Optional[Action]: A directly executable Action object if a match is found, otherwise None.
        """
        
        if not self.knowledge_source:
            return None
            
        return self.knowledge_source.match_trace(screenshot_path, task)

    @abstractmethod
    def clear(self):
        """
        Reset the memory state.
        Called when initializing a new agent or restarting a task.
        """
        pass

class BasePlanner(ABC):
    """
    Base interface for all planner modules.
    A planner module is responsible for generating a high-level plan from a given user task. 
    The plan describes *what* needs to be done, rather than how to execute each step.

    In the architecture, Planner produces a task-level or multi-step plan.
    """

    def __init__(self, llm_client: Any, knowledge_source: BaseKnowledgeSource = None, env_info: EnvironmentInfo = None):
        """Initialize the planner.
        

        Args:
            llm_client (Any): The language model client used for plan generation. This is an LLM adapter.
            knowledge_source (BaseKnowledgeSource, optional): An optional knowledge source that the planner may use for retrieving external or historical information. Defaults to None.
            env_info (EnvironmentInfo, optional): Static environment information, such as platform type and screen size, which may influence planning behavior. Defaults to None.
        """
        self.llm = llm_client
        self.knowledge_source = knowledge_source
        self.env = env_info
    
    @abstractmethod
    def make_plan(self, plan_input: PlanInput) -> PlanResult:
        """Generate a high-level plan for the given task.
        This method takes a user task (and optional contextual information) and produces a PlanResult that outlines the overall strategy or steps required to complete the task.

        Args:
            plan_input (PlanInput): The input for planning, including:
            - task: the user task description
            - screenshot_path (optional): path to the current screen snapshot

        Returns:
            PlanResult: The output of the planner, containing:
            - content: a natural language description of the plan.
            - data: optional structured planning information, such as target application or step outlines.

        Notes for developers:
         - This method focuses on *task-level planning*, not low-level actions.
         - It may call LLMs or knowledge sources.
        """
        pass

    @abstractmethod
    def _load_prompt(self, filename: str) -> str:
        """Load a prompt template used by the planner. This helper method allows planners to externalize prompt templates into files, 
        making them easier to manage, reuse, and modify without changing code.

        Args:
            filename (str): The name or path of the prompt template file.

        Returns:
            str: The content of the prompt template as a string.

        If filename is md, your can refer to unimobile/agents/components/planner/universal_planner.py _load_prompy function

        """
        pass

class BaseReason(ABC):
    def __init__(self, llm_client: Any, env_info: EnvironmentInfo = None):
        self.llm = llm_client
        self.env = env_info
    @abstractmethod
    def think(self, 
              task: str, 
              plan: PlanResult, 
              perception_result: PerceptionResult, 
              memory_context: List[MemoryFragment]) -> Action:
        pass

class BaseVerifier(ABC):
    @abstractmethod
    def verify(self, input_data: VerifierInput) -> VerifierResult:
        pass

class BasePlannerParser(ABC):
    @abstractmethod
    def parse(self, response: str, **kwargs) -> PlanResult:
        pass

class BaseActionParser(ABC):
    @abstractmethod
    def parse(self, response: str, metadata: dict) -> Action:
        raise NotImplementedError

# ==========================================
# 3. Top-level Interface
# ==========================================
class BaseAgent(ABC):
    """
    All agents whether Modular or externally integrated must comply with this standard
    Runner only recognizes this interface.
    """
    @abstractmethod
    def step(self, screenshot_path: str, width: int, height: int) -> Action:
        pass
    
    @abstractmethod
    def reset(self, task: str):
        pass


class BaseEvaluator(ABC):
    """所有评估节点的绝对基类 (包括 AST 节点和具体插件)"""
    _pipeline_phase = "⚖️ Evaluation"

    def __init__(self, params: Dict[str, Any], device: Any) -> None:
        self.params = params
        self.device = device
        
        # 自动挂载极简日志 (如果子类没有用装饰器，默认给个 unknown)
        ns = getattr(self.__class__, '__plugin_namespace__', 'evaluator.unknown')
        name = getattr(self.__class__, '__plugin_name__', self.__class__.__name__)
        self.logger = get_plugin_logger(phase=self._pipeline_phase, namespace=ns, plugin_name=name)

    def pre_evaluate(self, context: Dict[str, Any]) -> None:
        """前置动作（默认不干事，子类可覆盖）"""
        pass

    @abstractmethod
    def evaluate(self, context: Dict[str, Any]) -> EvalResult:
        """核心评估逻辑"""
        pass